In [42]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Flatten, Dense

In [43]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [44]:
dataset = pd.read_csv("Customer_Churn_Modelling.csv")
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [45]:
x = dataset.drop(labels=['CustomerId', 'Surname', 'RowNumber', 'Exited'], axis = 1)
y = dataset['Exited']

In [46]:
x.head(10)

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   
5          645     Spain    Male   44       8  113755.78              2   
6          822    France    Male   50       7       0.00              2   
7          376   Germany  Female   29       4  115046.74              4   
8          501    France    Male   44       4  142051.07              2   
9          684    France    Male   27       2  134603.88              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10  
5          1               0        149756.71  
6          1               1         10062.80  
7          1               0        119346.88  
8          0               1         74940.50  
9          1               1         71725.73

In [47]:
y.head()

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

In [48]:
from sklearn.preprocessing import LabelEncoder

In [49]:
label1 = LabelEncoder()
x['Geography'] = label1.fit_transform(x['Geography'])

In [50]:
x.head(10)

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619          0  Female   42       2       0.00              1   
1          608          2  Female   41       1   83807.86              1   
2          502          0  Female   42       8  159660.80              3   
3          699          0  Female   39       1       0.00              2   
4          850          2  Female   43       2  125510.82              1   
5          645          2    Male   44       8  113755.78              2   
6          822          0    Male   50       7       0.00              2   
7          376          1  Female   29       4  115046.74              4   
8          501          0    Male   44       4  142051.07              2   
9          684          0    Male   27       2  134603.88              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10  
5          1               0        149756.71  
6          1               1         10062.80  
7          1               0        119346.88  
8          0               1         74940.50  
9          1               1         71725.73

In [51]:
label = LabelEncoder()
x['Gender'] = label1.fit_transform(x['Gender'])

In [52]:
x.head(10)

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619          0       0   42       2       0.00              1   
1          608          2       0   41       1   83807.86              1   
2          502          0       0   42       8  159660.80              3   
3          699          0       0   39       1       0.00              2   
4          850          2       0   43       2  125510.82              1   
5          645          2       1   44       8  113755.78              2   
6          822          0       1   50       7       0.00              2   
7          376          1       0   29       4  115046.74              4   
8          501          0       1   44       4  142051.07              2   
9          684          0       1   27       2  134603.88              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10  
5          1               0        149756.71  
6          1               1         10062.80  
7          1               0        119346.88  
8          0               1         74940.50  
9          1               1         71725.73

In [53]:
x = pd.get_dummies(x, drop_first=True, columns=['Geography'])
x.head()

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619       0   42       2       0.00              1          1   
1          608       0   41       1   83807.86              1          0   
2          502       0   42       8  159660.80              3          1   
3          699       0   39       1       0.00              2          0   
4          850       0   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Geography_1  Geography_2  
0               1        101348.88            0            0  
1               1        112542.58            0            1  
2               0        113931.57            0            0  
3               0         93826.63            0            0  
4               1         79084.10            0            1

In [54]:
###Feature Standardization (In order to bring feature values in same scale)

In [55]:
from sklearn.preprocessing import StandardScaler

In [56]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0, stratify = y)

In [57]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [58]:
x_train

array([[-1.24021723, -1.09665089,  0.77986083, ...,  1.64099027,
        -0.57812007, -0.57504086],
       [ 0.75974873,  0.91186722, -0.27382717, ..., -1.55587522,
         1.72974448, -0.57504086],
       [-1.72725557, -1.09665089, -0.9443559 , ...,  1.1038111 ,
        -0.57812007, -0.57504086],
       ...,
       [-0.51484098,  0.91186722,  0.87565065, ..., -1.01507508,
         1.72974448, -0.57504086],
       [ 0.73902369, -1.09665089, -0.36961699, ..., -1.47887193,
        -0.57812007, -0.57504086],
       [ 0.95663657,  0.91186722, -1.32751517, ...,  0.50945854,
        -0.57812007,  1.73900686]])

In [59]:
#Build ANN

In [60]:
model = Sequential()
model.add(Dense(x.shape[1], activation='relu', input_dim = x.shape[1]))
model.add(Dense(128, activation='relu'))
model.add(Dense(1, activation = 'sigmoid'))

In [61]:
x.shape[1]

11

In [62]:
model.compile(optimizer='adam', loss = 'binary_crossentropy', metrics=['accuracy'])

In [63]:
model.fit(x_train, y_train.to_numpy(), batch_size = 10, epochs = 10, verbose = 1)

Epoch 1/10
800/800 [==============================] - 1s 1ms/step - loss: 0.4573 - accuracy: 0.8000
Epoch 2/10
800/800 [==============================] - 1s 2ms/step - loss: 0.4091 - accuracy: 0.8227
Epoch 3/10
800/800 [==============================] - 1s 2ms/step - loss: 0.3721 - accuracy: 0.8441
Epoch 4/10
800/800 [==============================] - 1s 1ms/step - loss: 0.3533 - accuracy: 0.8554
Epoch 5/10
800/800 [==============================] - 1s 1ms/step - loss: 0.3442 - accuracy: 0.8564
Epoch 6/10
800/800 [==============================] - 1s 1ms/step - loss: 0.3384 - accuracy: 0.8619
Epoch 7/10
800/800 [==============================] - 1s 1ms/step - loss: 0.3342 - accuracy: 0.8619
Epoch 8/10
800/800 [==============================] - 1s 1ms/step - loss: 0.3316 - accuracy: 0.8649
Epoch 9/10
800/800 [==============================] - 1s 1ms/step - loss: 0.3288 - accuracy: 0.8670
Epoch 10/10
800/800 [==============================] - 1s 2ms/step - loss: 0.3265 - accuracy: 0.8629

In [64]:
y_pred = model.predict_classes(x_test)

In [65]:
y_pred

array([[0],
       [0],
       [0],
       ...,
       [0],
       [1],
       [0]])

In [66]:
y_test

1344    1
8167    0
4747    0
5004    1
3124    1
       ..
9107    0
8249    0
8337    0
6279    1
412     0
Name: Exited, Length: 2000, dtype: int64

In [67]:
model.evaluate(x_test, y_test.to_numpy())

63/63 [==============================] - 0s 1ms/step - loss: 0.3498 - accuracy: 0.8550


[0.3498121201992035, 0.8550000190734863]

In [68]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [69]:
confusion_matrix(y_test, y_pred)

array([[1524,   69],
       [ 221,  186]], dtype=int64)

In [70]:
accuracy_score(y_test, y_pred)

0.855